# Generated by Django 3.1.7 on 2021-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_Date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_rooms', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Bookings',
                'ordering': ['from_Date'],
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_Type', models.CharField(choices=[('KS', 'King')], max_length=10)),
            ],
        ),
    ]
